# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
# Build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'vishwaraj00/php-8.0-apache-grpc-protobuf', './server']
  timeout: 9000s

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push',
          'vishwaraj00/php-8.0-apache-grpc-protobuf']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'thebookclubserver', '--image', 'vishwaraj00/php-8.0-apache-grpc-protobuf:latest', '--region', 'asia-southeast1', '--port', '8080']

# # Simple sanity check: invoke the new gcloud container to confirm that it was
# # built correctly.
# - name: 'gcr.io/$PROJECT_ID/vishwarajanand/the_book_club_app'
#   args: ['info']

# - name: 'gcr.io/$PROJECT_ID/vishwarajanand/the_book_club_server'
#   args: ['info']

images:
- 'vishwaraj00/php-8.0-apache-grpc-protobuf'

timeout: 24000s

options:
  logging: CLOUD_LOGGING_ONLY
